blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='blog-index'),
    path('about/', views.aboutPage, name='blog-about'),
    path('posts/', views.posts, name='blog-posts'),
    path('posts/create', views.createPost, name='blog-createpost'),
    path('register/', views.registerPage, name='blog-register'),
    path('login/', views.loginPage, name='blog-login'),
    path('logout/', views.logoutUser, name='blog-logout'),
    path('posts/<int:post_id>', views.individualPost, name='blog-individualpost'),
    path('posts/update/<int:post_id>', views.updatePost, name='blog-updatepost'),
    path('posts/delete/<int:post_id>', views.deletePost, name='blog-deletepost'),

    # path('/', views.index, name='blog-index')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.title} | {self.author}'

blog/forms.py
from django import forms

#import models
from .models import Post


from django.contrib.auth.models import User
#importing the django user form 
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    class Meta: 
        model = Post
        fields = ['title', 'author', 'content']

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

#import models (so we can query from database)
from .models import Post

#import forms ( so we can display it in our template)
from .forms import PostForm, UserForm

#import extra functionality: (authentication/login/logout/messages)
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
#import mail dependencies
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

# Create your views here.
def index(request):
    my_posts = [
        {
            'author' : 'Shoha Tsuchida',
            'title': 'This is my first post!',
            'content' : 'content1',
            'date_posted' : 'August 9, 2021'
        },
        {
            'author' : 'Ivan Wang',
            'title': "This is Ivan's first post!",
            'content' : 'content from Ivan',
            'date_posted' : 'August 9, 2021'
        }
    ]
    context = {'posts': my_posts}
    # <!-- Syntax for adding python vars: {{ var_goes here}}-->
    # <!-- Syntax for adding python vars: {% expression_goes_here %}-->
    return render(request, 'blog/index.html', context)

def aboutPage(request):
    return render(request, 'blog/about.html')

def posts(request):
    posts = Post.objects.order_by('id').all()
    context = {
        'posts': posts,
        'page_title' : 'Welcome to my blog'
    }
    return render(request, 'blog/posts.html', context)

@login_required(login_url='blog-login')
def createPost(request):
    form = PostForm(request.POST or None)
    if form.is_valid(): 
        form.save() 
    context = {
        'form': form
    }
    return render(request, 'blog/createpost.html', context)

def registerPage(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        print('form submitted')
        form.save()


        user = form.cleaned_data.get('username')
        email = form.cleaned_data.get('email')

        context = {"username" : user}

        template = render_to_string('blog/emailtemplate.html', context)

        email_message = EmailMessage(
            'Welcome to my Django Blog!', #Subject Line
            template, #body
            settings.EMAIL_HOST_USER, #host_email
            [email], #recipient
        )

        email_message.fail_silently = False 
        email_message.send() 

        messages.success(request, "Account was created for " + user)

        return redirect('blog-login')
    context = { 'form': form}
    return render(request, 'blog/register.html', context)

def loginPage(request):
    if request.method == "POST":
        username = request.POST.get("username") #comes from name attribute in html input tag
        password = request.POST.get("password1")
        print(username,password)
        user= authenticate(request, username = username, password = password)
        print(user)
        if user is not None:
            login(request, user)
            print(f'{user} is logged in.')
            return redirect('blog-index')
        messages.info(request, "Incorrect username or password. Please try again.")
    return render(request,'blog/login.html')

@login_required(login_url = 'blog-login')
def logoutUser(request):
    logout(request)
    return redirect('blog-login')

def individualPost(request, post_id):
    post = Post.objects.get(id=post_id)
    context ={'p':post}
    return render(request, 'blog/individualpost.html', context)

@login_required(login_url = 'blog-login')
def updatePost(request,post_id):
    post = Post.objects.get(id=post_id)
    form = PostForm(instance=post)
    if post.author.id != request.user.id and not request.user.is_superuser:
            messages.info(request, "You can not update another user's post!")
            return redirect('blog-posts')
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "You have successfully updated your post.")
        return redirect('blog-individualpost', post_id=post_id)
    context = {'form': form}
    return render(request, 'blog/updatepost.html', context)

@login_required(login_url = 'blog-login')
def deletePost(request, post_id):
    post = Post.objects.get(id=post_id)
    if post.author.id != request.user.id:
        messages.info(request, "You can not delete another user's post!")
        return redirect('blog-posts')
    post.delete() 
    messages.success(request, "The post has been successfully deleted.")
    return redirect('blog-posts')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
    
<h1>This is the about page</h1>

{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{% static 'blog/main.css' %}">
<title>Title</title>
</head>
<body>
    {% include 'blog/nav.html' %}
    <div class='container'>
    {% block content %}

    {% endblock %}
    </div>
    {% include 'blog/footer.html' %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog/createpost.html
{% extends 'blog/base.html' %}
{% block content %}
<div class=form-border-box>
    <h2>Create a post</h2>
    <form method="POST">
        
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title :</label>
            <input type="text" name="title" maxlength="255" required='' class="form-control" id="id_title">
        </div>
        <div class="d-none">
            <input type="text" name="author" required='' value= "{{ request.user.id }}" id="id_author">
        </div>
        <div class="mb-3">
            <label for="id_content" class="form-label">Content :</label>
            <textarea name="content" required='' cols='40' rows='10' class="form-control" id="id_content"></textarea>
        </div>

        <input type='submit' value = 'Submit'>

    </form>
</div>

{% endblock %}

blog/templates/blog/emailtemplate.html
Hey {{username}},

Thank you for signing up to my Django Blog! 
Looking forward to see you expressing yourself here.

Regards,
The Blog Guy

blog/templates/blog/footer.html
<footer>
    <p> Footer</p>
</footer>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>This is our new index page!</h1>
    {% for post in posts %}

        {% if post.author == "Ivan Wang" %}
            <h2> The Best Instructor</h2>
        {% endif %}
        
        <h3>{{ post.title }}</h3>
        <h5>By {{ post.author }} on {{ post.date_posted }}</h5>
        <h5>{{ post.content }}</h5>
    {% endfor %}

{% endblock %}

blog/templates/blog/individualpost.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="card">
    <div class="card-body">
      <h5 class="card-title">{{ p.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ p.author }}</h6>
      <p class="card-text">{{ p.content }}</p>
      <p class="card-text">{{ p.date_posted }}</p>
    </div>
    {% if request.user.id == p.author.id %}
    <div class="container">
        <!-- update button -->
        <a href="{% url 'blog-updatepost' post_id=p.id %}" class="btn btn-primary">Update</a>
    
        <!-- delete modal -->
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Delete
        </button>
    
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Post - Are you sure?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                This action cannot be reversed. Are you sure you want to delete?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                
                <form action="{% url 'blog-deletepost' post_id=p.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% for message in messages %}
<p class='messages {{ message.tags }}'>{{ message }}</p>
{% endfor %} 
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
<div class='form-border-box'>
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Username :</label>
            <input type="text" name="username" maxlength="150" class="form-control" id="id_username">
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Password :</label>
            <input type="password" name="password1" autocomplete='new-password' maxlength="150" class="form-control" id="id_password1">
        </div>

        <input type='submit' class='btn btn-primary' value = 'Submit'>

    </form>
</div>
{% for message in messages %}
<p class='messages {{ message.tags }}'>{{ message }}</p>
{% endfor %} 
<div class='mt-2 text-center'>Don't have an account? <a class='text-drecoration-none' href="{% url 'blog-register' %}">Sign Up</a></div>
{% endblock %}

blog/templates/blog/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog-index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog-about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog-posts' %}">Posts</a>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog-createpost' %}">Create Posts</a>
          </li>
          <span class="nav-link float-end">Hello, {{ request.user }}</span>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog-logout' %}">Logout</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog-register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog-login' %}">Login</a>
          </li>
          {% endif %}
          
        </ul>
      </div>
    </div>
</nav>

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>{{ page_title }}</h1>

{% for message in messages %}
<p class='messages {{ message.tags }}'>{{ message }}</p>
{% endfor %} 
{% for p in posts %}

        <div class="card">
            <div class="card-body">
              <a class="text-decoration-none" href="{% url 'blog-individualpost' post_id=p.id %}" >
                <h5 class="card-title">{{ p.title }}</h5>
              </a>
              <h6 class="card-subtitle mb-2 text-muted">{{ p.author }}</h6>
              <p class="card-text">{{ p.content }}</p>
              <p class="card-text">{{ p.date_posted }}</p>
            </div>
        </div>

        

{% endfor %}
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% block content %}
<div class='form-border-box'>
    <h2>Register</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Username :</label>
            <input type="text" name="username" maxlength="150" class="form-control" id="id_username">
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Email :</label>
            <input type="text" name="email" maxlength="150" class="form-control" id="id_email">
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Password :</label>
            <input type="password" name="password1" autocomplete='new-password' maxlength="150" class="form-control" id="id_password1">
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label">Password confirmation :</label>
            <input type="password" name="password2" autocomplete='new-password' maxlength="150" class="form-control" id="id_password2">
        </div>



        <input type='submit' class='btn btn-primary' value = 'Submit'>

    </form>
</div>

{{ form.errors }}
<div class='mt-2 text-center'>Already have an account? <a class='text-drecoration-none' href="{% url 'blog-login' %}">Log In</a></div>
{% endblock %}

blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% block content %}
<div class=form-border-box>
    <h2>Update post</h2>
    <form method="POST">
        
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title :</label>
            <input type="text" name="title" maxlength="255" required='' class="form-control" id="id_title">
        </div>
        <div class="d-none">
            <input type="text" name="author" required='' value= "{{ request.user.id }}" id="id_author">
        </div>
        <div class="mb-3">
            <label for="id_content" class="form-label">Content :</label>
            <textarea name="content" required='' cols='40' rows='10' class="form-control" id="id_content"></textarea>
        </div>

        <input type='submit' class="btn btn-primary" value = 'Submit'>

    </form>
</div>

{% endblock %}